### PR TITLE
E2E tests added

### PR DESCRIPTION
**Pull request by Madhan-SWE**
Fixes: --

### CODE REVIEW

**Comment by mkumatag** [comment]
test is working fine :P
/approve cancel

**Review by mkumatag — CHANGES_REQUESTED** [review]
As requested lets split this PR into multiple
- one with package updates
- PR with e2e tests

**Comment by mkumatag** [comment]
can this be closed?

**Comment by Madhan-SWE** [comment]
This PR can be closed as it is not suitable for merging.

**Pull request closed without merging**
